---
version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pip3 install --upgrade cfn-lint

      # Install cfn_nag
      - gem install cfn-nag
      - node -v
      - npm -v

      # https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib

  pre_build:
    commands:
      - echo "pre_build steps for revision ${CODEBUILD_RESOLVED_SOURCE_VERSION}..."
      - pwd
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_SRC_DIR
      - env
      - node -v
      - aws --version
      - cfn-lint -v
      - cfn_nag -v

      # Lint
      - cfn-lint # uses .cfnlintrc

      # Run cfn-nag (looks for patterns in CFN templates that may indicate insecure infrastructure)
      - cfn_nag_scan --output-format txt --print-suppression --fail-on-warnings --blacklist-path .cfn_nag_blacklist --input-path . --template-pattern '^(?!.*buildspec.*)((..*\.y[a]?ml)|(..*\.template))$'

      - npm ci

  build:
    commands:
      - echo Build started on `date`
      - echo Building Node app...
      - npm run build
      - CI=true npm run test:cypress

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Files
      - ls -la

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - '/node_modules/**/*'
